% config_s32r45.m
% This script preloads Python Gold Algorthmic Model data and sets up fixed-point types for S32R45 SPT

% 1. To prevent path errors
script_dir = fileparts(mfilename('fullpath'));

% Construct absolute paths 
input_data_path = fullfile(script_dir, '..', 'python_prototype', 'data', 'radar_input.mat');

% Check if the file exists
if ~exist(input_data_path, 'file')
    error('Target file not found at: %s. Did you run the Python script first?', input_data_path);
end

% Load the data generated by the Python script
load(input_data_path);

% 2. Definition of Radar System Dimensions
NUM_SAMPLES = 128; % Fast-time (Range Bins)
NUM_CHIRPS = 64;   % Slow-time (Doppler Bins)

% 3. Format Data into Time-Series Structures for Simulink Ingestion
time_vector = (0:NUM_CHIRPS-1)'; % One frame slice per chirp step
% Simulink From Workspace block expects [Time, Data] or a structure
% We pass the data frame as a 128x64 matrix directly

raw_frame_real = struct('time', 0, 'signals', struct('values', raw_cube_real, 'dimensions', [NUM_SAMPLES, NUM_CHIRPS]));
raw_frame_imag = struct('time', 0, 'signals', struct('values', raw_cube_imag, 'dimensions', [NUM_SAMPLES, NUM_CHIRPS]));

% 4. Emulate S32R45 SPT 3.1 Hardware Constraints (16-bit Fixed-Point)
% Signed, 16-bit total word length, 
% 14 bits fraction length (leaves 1 bit for sign, 1 for integer)

spt_fxp_type = fixdt(1, 16, 14); 

fprintf('[MATLAB] S32R45 Workspace configuration loaded successfully.\n');
